{% set python_min = "3.11" %}
{% set name = "simmate" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d63d58069c4f779d7fed1461303934bf2e08df414f76b51557e7435225ea97d3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - simmate = simmate.command_line.base_command:simmate_app
    - simmate-vasp = simmate.apps.vasp.command_line.base_command:vasp_app
    - simmate-qe = simmate.apps.quantum_espresso.command_line.base_command:qe_app

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.12
    - numpy >=2.0.0,<3.0.0
    - pandas >=2.0.0,<3.0.0
    - django >=5.2.11,<6.0.0
    - typer >=0.24.1,<0.25.0
    - psycopg2-binary >=2.9.11,<3.0.0
    - pymatgen >=2025.10.7,<2025.10.8
    - pymatgen-analysis-diffusion >=2025.11.15,<2025.11.16
    - matminer >=0.10.0,<0.11.0
    - ase >=3.22.1,<3.23.0
    - rdkit >=2025.9.5,<2025.9.6
    - ipython >=8.22.2,<10.0.0
    - django-allauth >=0.63.3,<0.64.0
    - django-simple-history >=3.11.0,<3.12.0
    - pyyaml >=6.0.3,<7.0.0
    - plotly >=6.5.0,<7.0.0
    - markdown >=3.4.1,<4.0.0
    - requests >=2.32.5,<3.0.0
    - scikit-learn >=1.1.1,<2.0.0
    - cloudpickle >=3.1.2,<=4.0.0
    - rich >=14.3.3,<15.0.0
    - toml >=0.10.2,<0.11.0
    - schedule >=1.2.2,<2.0.0
    - xmltodict >=1.0.4,<2.0.0
    - dask-core >=2026.1.2,<2026.1.3
    - distributed >=2026.1.2,<2026.1.3
    - beautifulsoup4 >=4.0.0,<5.0.0
    - cachetools >=7.0.1,<8.0.0
    - umap-learn >=0.5.5,<0.6.0

test:
  imports:
    - simmate
    - simmate.apps
    - simmate.command_line
    - simmate.config
    - simmate.database
    - simmate.toolkit
    - simmate.utils
    - simmate.website
    - simmate.workflows
  requires:
    - pip
    - python {{ python_min }}
  #   - pytest >=6.2.5, <=7.1.2
  #   - pytest-django >=4.5.2, <=4.5.2
  #   - pytest-mock >=3.7.0, <=3.8.2
  #   - pytest-xdist >=2.5.0, <=2.5.0
  # source_files:
  #   - test
  commands:
    # - pip check  # BUG: matminer isn't printing proper version
    - simmate --help
    # - pytest --no-migrations --durations=15 -m 'not blender and not vasp'

about:
  home: https://simmate.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simmate is a full-stack framework for chemistry research.
  description: |
    Simmate is a full-stack framework for chemistry research. It helps you calculate
    properties and explore third-party databases for both for molecular and 
    crystalline systems. For experts, it also provides a toolbox to build out
    your own chemistry applications.
  doc_url: https://jacksund.github.io/simmate/home/
  dev_url: https://github.com/jacksund/simmate

extra:
  recipe-maintainers:
    - jacksund
