{% set name = "simmate" %}
{% set version = "0.0.0.dev5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf54c259532f21f6071f0be4d0694bfab09cc72b7a9edf563805a527d53f37fe

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
      - simmate = simmate.command_line.base_command:simmate

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.21.4
    - pandas >=1.3.5
    - django ==3.2.10
    - prefect ==0.15.11
    - dask >=2021.12.0
    - click >=8.0.3
    - numba >=0.53.0
    - django-crispy-forms >=1.13.0
    - django-pandas >=0.6.1
    - dask-jobqueue >=0.7.3
    - scikit-learn >=1.0.1
    - dj-database-url >=0.5.0
    - djangorestframework ==3.13.1
    - django-filter >=21.1
    - django-extensions >=3.1.5
    - pyyaml >=6.0
    - pytest >=6.2.5
    - black >=21.12b0
    - plotly ==5.4.0
    - pymatgen ==2022.0.17
    - pymatgen-analysis-diffusion ==2021.4.29
    - matminer >=0.7.4

test:
  imports:
    # only test a base import for now
    - simmate
  requires:
    - pip
  commands:
    - pip check
    - simmate --help

about:
  home: https://github.com/jacksund/simmate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Simmate is a toolbox for computational materials research.'
  # Still setting things up, so these will be added later.
  # description: |
  #   The Simulated Materials Ecosystem (Simmate) is a toolbox for computational
  #   materials research. It lets you explore various crystal databases, predict
  #   new materials, and quickly calculate properties (electronic, elastic, 
  #   thermodynamic, and more).
  # doc_url: https://simplejson.readthedocs.io/
  # dev_url: https://github.com/jacksund/simmate

extra:
  recipe-maintainers:
    - jacksund
