{% set name = "simmate" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b7cbba704ad4ee4484ee10ff328b2b15880962b1813ea37665eda84e71da435

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - simmate = simmate.command_line.base_command:simmate

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.10
    - pip
  run:
    - black >=22.1.0, <=22.6.0
    - click >=8.0.3, <=8.1.3
    - coverage >=6.2, <=6.4.3
    - dask-core >=2021.12.0, <=2022.8.0
    - dask-jobqueue >=0.7.3, <=0.7.4
    - dj-database-url >=0.5.0, <=0.5.0
    - django >=4.0.0, <=4.1.0
    - django-allauth >=0.50.0, <=0.51.0
    - django-crispy-forms >=1.13.0, <=1.14.0
    - django-pandas >=0.6.6, <=0.6.6
    - django-filter >=21.1, <=22.1
    - djangorestframework >=3.13.1, <=3.13.1
    - isort >=5.10.1, <=5.10.1
    - matminer >=0.7.6, <=0.7.8
    - nest-asyncio >=1.5.5, <=1.5.5
    - numpy >=1.22.0, <=1.23.1
    - pandas >=1.3.5, <=1.4.3
    - pdoc >=11.0.0, <=12.0.2
    - plotly >=5.4.0, <=5.9.0
    - prefect >=2.0.0, <=2.0.4
    - pymatgen >=2022.1.9, <=2022.7.25
    - pymatgen-analysis-diffusion >=2021.4.29, <=2022.7.21
    - pytest >=6.2.5, <7.1
    - pytest-django >=4.5.2, <=4.5.2
    - python >=3.10
    - pytest-mock >=3.7.0, <=3.8.2
    - pytest-xdist >=2.5.0, <=2.5.0
    - pyyaml >=6.0, <=6.0
    - tqdm >=4.62.3, <=4.64.0

test:
  imports:
    # only test a base import for now
    - simmate
  requires:
    - pip
  commands:
    # `pip check` fails on `readchar` which has a different identifier when provided by conda
    # A `--ignore` flag is in progress at https://github.com/pypa/pip/pull/11159 which will
    # allow us to enable this check again while excluding readchar
    # This error is also present in the Prefect feedstock
    #   https://github.com/conda-forge/prefect-feedstock/blob/f4b43b02aceb2bb213bdea491ed7002d7004819b/recipe/meta.yaml#L68-L71
    # - pip check
    - simmate --help

about:
  home: https://github.com/jacksund/simmate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simmate is a toolbox and framework for computational materials research.
  description: |
    The Simulated Materials Ecosystem (Simmate) is a toolbox and framework for 
    computational materials research. It lets you explore various crystal 
    databases, predict new materials, and quickly calculate properties 
    (electronic, elastic, thermodynamic, and more).
  doc_url: https://jacksund.github.io/simmate/simmate.html
  dev_url: https://github.com/jacksund/simmate

extra:
  recipe-maintainers:
    - jacksund
