{% set name = "simmate" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b435499defa8a37c965f4add53f78ad3def0cf7403328ef9580d441326eeda5a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - simmate = simmate.command_line.base_command:simmate

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.10
    - pip
  run:
    - ase >=3.22.1, <=3.22.1
    - cloudpickle >=2.1.0, <=2.1.0
    - dask-core >=2021.12.0, <=2022.8.0
    - distributed >=2022.7.1, <=2022.8.0
    - dj-database-url >=0.5.0, <=0.5.0
    - django >=4.0.0, <=4.1.0
    - django-allauth >=0.50.0, <=0.51.0
    - django-crispy-forms >=1.13.0, <=1.14.0
    - django-pandas >=0.6.6, <=0.6.6
    - django-filter >=21.1, <=22.1
    - djangorestframework >=3.13.1, <=3.13.1
    - matminer >=0.7.6, <=0.7.8
    - markdown >=3.4.1, <=3.4.1
    - numpy >=1.22.0, <=1.23.1
    - pandas >=1.3.5, <=1.4.3
    - plotly >=5.4.0, <=5.9.0
    - pymatgen >=2022.1.9, <=2022.7.25
    - pymatgen-analysis-diffusion >=2021.4.29, <=2022.7.21
    - python >=3.10
    - pyyaml >=6.0, <=6.0
    - requests >=2.28.1, <=2.28.1
    - rich >=11.0, <=12.5.1
    - scikit-learn >=1.1.1, <=1.1.1
    - typer >=0.4.1, <=0.6.1

test:
  imports:
    # only test a base import for now
    - simmate
  requires:
    - pip
  commands:
    - pip check
    - simmate --help

about:
  home: https://github.com/jacksund/simmate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simmate is a toolbox and framework for computational materials research.
  description: |
    The Simulated Materials Ecosystem (Simmate) is a toolbox and framework for 
    computational materials research. It lets you explore various crystal 
    databases, predict new materials, and quickly calculate properties 
    (electronic, elastic, thermodynamic, and more).
  doc_url: https://jacksund.github.io/simmate/simmate.html
  dev_url: https://github.com/jacksund/simmate

extra:
  recipe-maintainers:
    - jacksund
