{% set name = "simmate" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 167b495ae45c39c11ec40b3347cee741dd67b503c3304179be66d0623d881189

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - simmate = simmate.command_line.base_command:simmate_app

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.10
    - pip
  run:
    - ase >=3.22.1, <=3.22.1
    - cloudpickle >=2.1.0, <=3.0.0
    - dask-core >=2023.6.1, <2023.11.1
    - distributed >=2023.6.1, <2023.11.1
    - dj-database-url >=0.5.0, <1.4.0
    - django >=4.0.0, <4.2.8
    - django-allauth >=0.56.0, <=0.58.0
    - django-contrib-comments >=2.2.0, <=2.2.0
    - django-crispy-forms >=1.13.0, <=1.14.0
    - django-pandas >=0.6.6, <=0.6.6
    - django-filter >=21.1, <=22.1
    - django_unicorn >=0.50.0, <=0.55.0
    - django-simple-history >=3.3.0, <=3.3.0
    - djangorestframework >=3.13.1, <3.14.1
    - matminer >=0.7.6, <0.8.1
    - markdown >=3.4.1, <=3.5.1
    - mp-pyrho >=0.3.0, <=0.3.0
    - numpy >=1.22.0, <1.24.2
    - pandas >=2.0.0, <2.1.4
    - plotly >=5.4.0, <5.17.0
    - pymatgen >=2022.1.9, <2023.5.32
    - pymatgen-analysis-diffusion >=2021.4.29, <=2023.8.15
    - python >=3.10
    - pyyaml >=6.0, <=6.0.1
    - requests >=2.28.1, <2.28.3
    - rich >=11.0, <=13.5.2
    - scikit-learn >=1.1.1, <1.2.2
    - schedule >=1.2.0, <=1.2.0
    - toml >=0.10.2, <=0.10.2
    - typer >=0.6.0, <0.7.1
    - xmltodict >=0.13.0, <=0.13.0

test:
  imports:
    - simmate
    - simmate.apps
    - simmate.command_line
    - simmate.configuration
    - simmate.database
    - simmate.file_converters
    - simmate.toolkit
    - simmate.utilities
    - simmate.visualization
    - simmate.website
    - simmate.engine
    - simmate.workflows
  requires:
    - pip
  #   - pytest >=6.2.5, <=7.1.2
  #   - pytest-django >=4.5.2, <=4.5.2
  #   - pytest-mock >=3.7.0, <=3.8.2
  #   - pytest-xdist >=2.5.0, <=2.5.0
  # source_files:
  #   - test
  commands:
    # - pip check  # BUG: matminer isn't printing proper version
    - simmate --help
    # - pytest --no-migrations --durations=15 -m 'not blender and not vasp'

about:
  home: https://simmate.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simmate is a toolbox and framework for computational materials research.
  description: |
    The Simulated Materials Ecosystem (Simmate) is a toolbox and framework for 
    computational materials research. It lets you explore various crystal 
    databases, predict new materials, and quickly calculate properties 
    (electronic, elastic, thermodynamic, and more).
  doc_url: https://jacksund.github.io/simmate/home/
  dev_url: https://github.com/jacksund/simmate

extra:
  recipe-maintainers:
    - jacksund
