{% set name = "simmate" %}
{% set version = "0.0.0.dev10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3dd86ee8f2497873d2dba90be28b9d5e011628e722dcf3f216b1eaf22d3843b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
      - simmate = simmate.command_line.base_command:simmate

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.7
    - pip
  run:
    - black >=21.12b0
    - click >=8.0.3
    - dask-core >=2021.12.0
    - dask-jobqueue >=0.7.3
    - dj-database-url >=0.5.0
    - django >=3.2.10
    - django-crispy-forms >=1.13.0
    - django-extensions >=3.1.5
    - django-filter >=21.1
    - django-pandas >=0.6.1
    - djangorestframework >=3.13.1
    - jsonschema >=4.2.1
    - matminer >=0.7.4
    - numba >=0.53.0
    - numpy >=1.21.4
    - pandas >=1.3.5
    - plotly >=5.4.0
    - prefect >=0.15.11
    - pymatgen >=2022.0.16
    - pymatgen-analysis-diffusion >=2021.4.29
    - pytest >=6.2.5
    - python >=3.7
    - pyyaml >=6.0
    - tqdm >=4.62.3

test:
  imports:
    # only test a base import for now
    - simmate
  requires:
    - pip
  commands:
    - pip check
    - simmate --help

about:
  home: https://github.com/jacksund/simmate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Simmate is a toolbox for computational materials research.'
  # Still setting things up, so these will be added later.
  # description: |
  #   The Simulated Materials Ecosystem (Simmate) is a toolbox for computational
  #   materials research. It lets you explore various crystal databases, predict
  #   new materials, and quickly calculate properties (electronic, elastic, 
  #   thermodynamic, and more).
  # doc_url: https://simplejson.readthedocs.io/
  # dev_url: https://github.com/jacksund/simmate

extra:
  recipe-maintainers:
    - jacksund
