{% set python_min = "3.10" %}
{% set name = "simmate" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5910b1cd27a4efd0cdb0bd03636fd57b7eb108da7d01b03add2e34ecb4d2257

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - simmate = simmate.command_line.base_command:simmate_app
    - simmate-vasp = simmate.apps.vasp.command_line.base_command:vasp_app
    - simmate-qe = simmate.apps.quantum_espresso.command_line.base_command:qe_app

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python {{ python_min }}
    - pip
  run:
    - ase >=3.22.1, <=3.23.0
    - cloudpickle >=2.1.0, <=3.0.0
    - dask-core >=2023.6.1, <2024.4.3
    - distributed >=2023.6.1, <2024.4.3
    - dj-database-url >=0.5.0, <1.4.0
    - django >=4.0.0, <4.2.8
    - django-allauth >=0.56.0, <=0.63.3
    - django-contrib-comments >=2.2.0, <=2.2.0
    - django-crispy-forms >=1.13.0, <=1.14.0
    - django-filter >=21.1, <=22.1
    - beautifulsoup4 >=4.8.0
    - orjson >=3.6.0
    - shortuuid >=1.0.1
    - cachetools >=4.1.1
    - decorator >=4.4.2
    - django-simple-history >=3.3.0, <=3.3.0
    - djangorestframework >=3.13.1, <3.15.2
    - ipython >=8.22.2, <=8.29.0
    - matminer >=0.9.3, <=0.9.3
    - markdown >=3.4.1, <=3.5.1
    - numpy >=1.22.0, <1.24.2
    - pandas >=2.0.0, <2.1.4
    - plotly >=5.4.0, <5.19.0
    - pymatgen >=2022.1.9, <2023.5.32
    - pymatgen-analysis-diffusion >=2021.4.29, <=2023.8.15
    - python >={{ python_min }}
    - pyyaml >=6.0, <=6.0.1
    - rdkit >=2024.03.1, <=2024.03.1
    - requests >=2.28.1, <=2.32.3
    - rich >=11.0, <=13.5.2
    - scikit-learn >=1.1.1, <1.5.1
    - schedule >=1.2.0, <=1.2.0
    - toml >=0.10.2, <=0.10.2
    - typer >=0.6.0, <0.7.1
    - xmltodict >=0.13.0, <=0.13.0

test:
  imports:
    - simmate
    - simmate.apps
    - simmate.command_line
    - simmate.configuration
    - simmate.database
    - simmate.file_converters
    - simmate.toolkit
    - simmate.utilities
    - simmate.visualization
    - simmate.website
    - simmate.engine
    - simmate.workflows
  requires:
    - pip
  #   - pytest >=6.2.5, <=7.1.2
  #   - pytest-django >=4.5.2, <=4.5.2
  #   - pytest-mock >=3.7.0, <=3.8.2
  #   - pytest-xdist >=2.5.0, <=2.5.0
  # source_files:
  #   - test
    - python {{ python_min }}
  commands:
    # - pip check  # BUG: matminer isn't printing proper version
    - simmate --help
    # - pytest --no-migrations --durations=15 -m 'not blender and not vasp'

about:
  home: https://simmate.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simmate is a full-stack framework for chemistry research.
  description: |
    Simmate is a full-stack framework for chemistry research. It helps you calculate
    properties and explore third-party databases for both for molecular and 
    crystalline systems. For experts, it also provides a toolbox to build out
    your own chemistry applications.
  doc_url: https://jacksund.github.io/simmate/home/
  dev_url: https://github.com/jacksund/simmate

extra:
  recipe-maintainers:
    - jacksund
